# Generated by Django 6.0 on 2026-02-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mdg',
            new_name='msg',
        ),
    ]
