# Generated by Django 6.0 on 2026-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_categories_add_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='iimg',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='add_product',
            name='desc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
